#!/usr/bin/python3
def raise_exception():
    print(1 + 'a')
    #    raise raise_exception
